# Generated by Django 4.2.7 on 2024-02-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_person_aadhardetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhardetail',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='order_management.person'),
        ),
    ]
