# Generated by Django 4.2.7 on 2024-02-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_alter_aadhardetail_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order_management.person'),
            preserve_default=False,
        ),
    ]
